version: "3.8"

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db


  backend:
    build:
      context: ../app/backend

    container_name: docker_backend

    restart: always

    ports:
      - "5000:3000"

    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      AWS_REGION: ap-south-1
      S3_BUCKET: clickops-bucket-dev

    volumes:
      - ~/.aws:/root/.aws:ro

    depends_on:
      - mongodb


  frontend:
    build:
      context: ../app/frontend

    container_name: docker_frontend

    restart: always

    ports:
      - "80:80"

    depends_on:
      - backend


volumes:
  mongo_data: