version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  backend:
    build: ../app/backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - ENV=dev
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb

  frontend:
    build: ../app/frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend